# Docker Compose 部署配置
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  aicore:
    build:
      context: ./aicore
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./aicore:/app

  smartui:
    build:
      context: ./smartui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AICORE_URL=http://aicore:8080
    depends_on:
      - aicore
    restart: unless-stopped

volumes:
  redis_data:
